version: '3'
services:
  serverless-mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - serverless-mongodb-data:/data/db
    networks:
      - microservices-serverless

  # event-mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "27018:27017"
  #   volumes:
  #     - event-mongodb-data:/data/db
  #   networks:
  #     - microservices-serverless
  #
  # registration-mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "27019:27017"
  #   volumes:
  #     - registration-mongodb-data:/data/db
  #   networks:
  #     - microservices-serverless

volumes:
  serverless-mongodb-data:
  # event-mongodb-data:
  # registration-mongodb-data:

networks:
  microservices-serverless:
    name: microservices-serverless
